#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p $HOME/.config/kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

mkdir -p $HOME/.config/nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc

touch $HOME/.p10k.zsh
rm $HOME/.p10k.zsh
ln -s $DOTFILES/zsh/p10k.zsh $HOME/.p10k.zsh
