#!/usr/bin/env bash
DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# wezterm
ln -sf $DOTFILES/wezterm/wezterm.lua $HOME/.wezterm.lua

# i3
rm -rf $HOME/.config/i3
ln -s $DOTFILES/i3 $HOME/.config/i3

# polybar
rm -rf $HOME/.config/polybar
ln -s $DOTFILES/polybar $HOME/.config/polybar

# rofi
rm -rf $HOME/.config/rofi
ln -s $DOTFILES/rofi $HOME/.config/rofi

# sublime
rm -rf $HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
mkdir -p $HOME/.config/sublime-text-3/Packages/User
ln -s $DOTFILES/sublime/Preferences.sublime-settings $HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

# neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# tmux
rm $HOME/.config/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.config/.tmux.conf

# zsh
rm $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc

# vimrc
rm $HOME/.vimrc
ln -s $DOTFILES/vim/vimrc $HOME/.vimrc

# p10k theme
rm $HOME/.p10k.zsh
ln -s $DOTFILES/zsh/p10k.zsh $HOME/.p10k.zsh

# git templates
ln -sf ~/dotfiles/git-templates ~/.git-templates
